import { useMemo, useState } from 'react';
import type { LightningEvent, Tower, WatchItem } from '../types';
import { db } from '../storage/db';
import { makeId } from '../utils/ids';
import { nowIso } from '../utils/time';
import { bearingBetween, haversineM } from '../triangulation/geometry';
import { clusterLightning, parseLightningCsv } from './lightning';

export default function LightningPanel({tower,events,onLook}:{tower:Tower;events:LightningEvent[];onLook?:(w:WatchItem)=>void}){
  const [lat,setLat]=useState('');const [lon,setLon]=useState('');const [error,setError]=useState('');const [recheckMinutes,setRecheckMinutes]=useState(30);
  const clusters=useMemo(()=>clusterLightning(events.filter(e=>['UNCHECKED','OBSCURED','POSSIBLE SMOKE','CONFIRMED FIRE'].includes(e.status))),[events]);
  async function add(){const a=Number(lat),o=Number(lon);if(!Number.isFinite(a)||!Number.isFinite(o))return;await db.lightning.add({id:makeId('strike'),timestamp:nowIso(),lat:a,lon:o,source:'MANUAL',status:'UNCHECKED'});setLat('');setLon('')}
  async function importCsv(file:File){try{const rows=parseLightningCsv(await file.text());await db.lightning.bulkAdd(rows.map(r=>({...r,id:makeId('strike')})));setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function watchCluster(c:(typeof clusters)[number]){const b=bearingBetween(tower,c),d=haversineM(tower,c);const w:WatchItem={id:makeId('watch'),title:`Lightning cluster · ${c.events.length} strike${c.events.length===1?'':'s'}`,priority:c.events.length>=5?'HIGH':'MEDIUM',reason:`Delayed-ignition visual check · ${(d/1609.344).toFixed(1)} mi · ${b.toFixed(0)}°`,dueAt:new Date(Date.now()+recheckMinutes*60000).toISOString(),targetBearing:b,targetLat:c.lat,targetLon:c.lon,status:'OPEN'};await db.watchItems.add(w);await db.shiftLogs.add({id:makeId('log'),timestamp:nowIso(),kind:'LIGHTNING',message:`Lightning cluster queued for visual recheck at ${b.toFixed(0)}°`});onLook?.(w)}
  return <section className="instrument-panel lightning-panel"><div className="section-kicker">LIGHTNING WATCH · v0.5</div><h2>Delayed ignition queue</h2><p className="instrument-help">Strikes persist as watch obligations after a storm. Import a small CSV or add a coordinate manually; FIREWATCH clusters nearby strikes locally.</p>
    <div className="lightning-import"><div className="form-grid"><label><span>Latitude</span><input value={lat} onChange={e=>setLat(e.target.value)} placeholder="39.52"/></label><label><span>Longitude</span><input value={lon} onChange={e=>setLon(e.target.value)} placeholder="-78.63"/></label></div><label className="setting-row lightning-cadence"><div><strong>Recheck delay</strong><small>Applied when a cluster is queued.</small></div><select value={recheckMinutes} onChange={e=>setRecheckMinutes(Number(e.target.value))}><option value={0}>Now</option><option value={30}>30 min</option><option value={60}>60 min</option><option value={120}>2 hr</option></select></label><div className="dual-actions"><button className="btn secondary" onClick={add}>Add strike</button><label className="btn secondary file-btn">Import CSV<input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/></label></div>{error&&<div className="inline-error">{error}</div>}</div>
    <div className="cluster-list">{clusters.length===0?<div className="empty">No open lightning events.</div>:clusters.map(c=>{const b=bearingBetween(tower,c),d=haversineM(tower,c);return <div className="cluster-row" key={c.id}><div><strong>{c.events.length} strike{c.events.length===1?'':'s'}</strong><span>{new Date(c.lastAt).toLocaleString()}</span><small>{b.toFixed(0)}° · {(d/1609.344).toFixed(1)} mi</small></div><div><button className="btn secondary" onClick={()=>watchCluster(c)}>Queue recheck</button><button className="btn ghost" onClick={()=>Promise.all(c.events.map(e=>db.lightning.update(e.id,{status:'NO SMOKE'})))}>No smoke</button></div></div>})}</div>
  </section>
}
