import { useMemo, useState } from 'react';
import Badge from '../components/Badge';
import { db } from '../storage/db';
import { useTable } from '../hooks';
import type { AppSettings, Landmark, Tower, WeatherObservation, WeatherSourceConfig } from '../types';
import { haversineM } from '../triangulation/geometry';
import { makeId } from '../utils/ids';
import { fmtDateTime } from '../utils/time';
import { pollWeatherSource, weatherFreshness } from './weather';

type Props={tower:Tower;landmarks:Landmark[];settings:AppSettings;onSettings:(p:Partial<AppSettings>)=>void};
const val=(s:string)=>s.trim()===''?undefined:Number(s);
export default function WeatherWorkspace({tower,landmarks,settings,onSettings}:Props){
  const weather=useTable(db.weather,'timestamp'),sources=useTable(db.weatherSources),vis=useTable(db.visibilityObservations,'timestamp');
  const latest=weather[0],fresh=weatherFreshness(latest);
  const [form,setForm]=useState({temperatureF:'',rh:'',windDir:'',windMph:'',gustMph:'',pressureInHg:'',precipIn:'',visibilityMi:'',cloudCover:'',notes:''});
  const [sourceName,setSourceName]=useState('Tower weather bridge'),[sourceUrl,setSourceUrl]=useState('http://127.0.0.1:8780/weather'),[sourceKind,setSourceKind]=useState<WeatherSourceConfig['kind']>('LOCAL SENSOR'),[polling,setPolling]=useState<string|null>(null);
  const landmarkRows=useMemo(()=>landmarks.map(l=>({...l,distanceMi:haversineM(tower,l)/1609.344,latest:vis.find(v=>v.landmarkId===l.id)})).sort((a,b)=>a.distanceMi-b.distanceMi),[landmarks,tower,vis]);
  const estimated=Math.max(0,...landmarkRows.filter(x=>x.latest?.visible).map(x=>x.distanceMi));
  async function saveManual(){const timestamp=new Date().toISOString();const row:WeatherObservation={id:makeId('wx'),timestamp,temperatureF:val(form.temperatureF),rh:val(form.rh),windDir:form.windDir||undefined,windMph:val(form.windMph),gustMph:val(form.gustMph),pressureInHg:val(form.pressureInHg),precipIn:val(form.precipIn),visibilityMi:val(form.visibilityMi),cloudCover:form.cloudCover||undefined,source:'MANUAL',sourceName:'Tower manual observation',receivedAt:timestamp,staleAfterMinutes:90,notes:form.notes||undefined};await db.weather.add(row);await db.shiftLogs.add({id:makeId('log'),timestamp,kind:'WEATHER',message:'Manual tower weather observation recorded'});setForm({temperatureF:'',rh:'',windDir:'',windMph:'',gustMph:'',pressureInHg:'',precipIn:'',visibilityMi:'',cloudCover:'',notes:''})}
  async function addSource(){if(!sourceName.trim()||!sourceUrl.trim())return;await db.weatherSources.add({id:makeId('wxsrc'),name:sourceName.trim(),kind:sourceKind,url:sourceUrl.trim(),enabled:true,pollMinutes:5,staleAfterMinutes:30});}
  async function setVisible(landmarkId:string,distanceMi:number,visible:boolean){const timestamp=new Date().toISOString();await db.visibilityObservations.add({id:makeId('vis'),timestamp,landmarkId,visible,distanceMi});await db.shiftLogs.add({id:makeId('log'),timestamp,kind:'VISIBILITY',message:`${landmarks.find(l=>l.id===landmarkId)?.name||landmarkId}: ${visible?'VISIBLE':'NOT VISIBLE'}`})}
  return <div className="weather-workspace">
    <div className="panel-header"><div><span className="section-kicker">WEATHER DESK · v0.7</span><h2>Tower conditions</h2></div><Badge tone={fresh==='LIVE'?'ok':fresh==='STALE'?'watch':'info'}>{fresh}</Badge></div>
    <div className="weather-current panel-inset">{latest?<><div className="weather-big"><strong>{latest.temperatureF!=null?`${Math.round(latest.temperatureF)}°F`:'—'}</strong><span>{latest.sourceName||latest.source}</span></div><div className="weather-facts"><span>RH <b>{latest.rh!=null?`${Math.round(latest.rh)}%`:'—'}</b></span><span>Wind <b>{latest.windDir||'—'} {latest.windMph!=null?Math.round(latest.windMph):'—'} mph</b></span><span>Gust <b>{latest.gustMph!=null?`${Math.round(latest.gustMph)} mph`:'—'}</b></span><span>Visibility <b>{latest.visibilityMi!=null?`${latest.visibilityMi.toFixed(0)} mi`:'—'}</b></span><span>Pressure <b>{latest.pressureInHg!=null?latest.pressureInHg.toFixed(2):'—'}</b></span><span>Observed <b>{fmtDateTime(latest.timestamp)}</b></span></div></>:<p>No weather observations recorded.</p>}</div>
    <section className="instrument-section"><span className="section-kicker">MANUAL OBSERVATION</span><div className="weather-form">{([['temperatureF','Temp °F'],['rh','RH %'],['windDir','Wind dir'],['windMph','Wind mph'],['gustMph','Gust mph'],['pressureInHg','Pressure inHg'],['precipIn','Precip in'],['visibilityMi','Visibility mi'],['cloudCover','Cloud cover']] as const).map(([k,label])=><label key={k}><span>{label}</span><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="wide"><span>Notes</span><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="btn primary" onClick={saveManual}>Record tower weather</button></section>
    <section className="instrument-section"><div className="panel-header"><div><span className="section-kicker">SOURCES</span><h3>Local sensor / remote JSON adapters</h3></div><label className="inline-toggle"><input type="checkbox" checked={settings.weatherAutoPoll} onChange={e=>onSettings({weatherAutoPoll:e.target.checked})}/> Auto poll</label></div><p className="instrument-help">Adapters accept FIREWATCH-style JSON and common field aliases. Localhost sensor bridges work offline from the Internet. Browser CORS rules still apply.</p><div className="source-add"><input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Source name"/><select value={sourceKind} onChange={e=>setSourceKind(e.target.value as WeatherSourceConfig['kind'])}><option>LOCAL SENSOR</option><option>REMOTE JSON</option></select><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="http://127.0.0.1:8780/weather"/><button className="btn secondary" onClick={addSource}>Add</button></div><div className="source-list">{sources.map(src=><div className="source-row" key={src.id}><div><strong>{src.name}</strong><small>{src.kind} · every {src.pollMinutes} min</small><small>{src.lastError?`ERROR · ${src.lastError}`:src.lastSuccessAt?`Last success ${fmtDateTime(src.lastSuccessAt)}`:'Never polled'}</small></div><label><input type="checkbox" checked={src.enabled} onChange={e=>db.weatherSources.update(src.id,{enabled:e.target.checked})}/> enabled</label><button className="btn ghost" disabled={polling===src.id} onClick={async()=>{setPolling(src.id);try{await pollWeatherSource(src)}catch{}finally{setPolling(null)}}}>{polling===src.id?'Polling…':'Poll now'}</button><button className="btn ghost" onClick={()=>db.weatherSources.delete(src.id)}>Remove</button></div>)}</div></section>
    <section className="instrument-section"><div className="panel-header"><div><span className="section-kicker">VISIBILITY REFERENCES</span><h3>{estimated?`Estimated visibility ≈ ${estimated.toFixed(0)} mi`:'Mark visible landmarks'}</h3></div></div><div className="visibility-list">{landmarkRows.map(l=><div className="visibility-row" key={l.id}><div><strong>{l.name}</strong><small>{l.distanceMi.toFixed(1)} mi · {l.latest?`${l.latest.visible?'VISIBLE':'NOT VISIBLE'} ${fmtDateTime(l.latest.timestamp)}`:'unchecked'}</small></div><button className="btn ghost" onClick={()=>setVisible(l.id,l.distanceMi,true)}>Visible</button><button className="btn ghost" onClick={()=>setVisible(l.id,l.distanceMi,false)}>Not visible</button></div>)}</div></section>
    <section className="instrument-section"><span className="section-kicker">RECENT WEATHER</span><div className="weather-history">{weather.slice(0,12).map(w=><div key={w.id}><time>{fmtDateTime(w.timestamp)}</time><strong>{w.temperatureF!=null?`${Math.round(w.temperatureF)}°F`:'—'} · RH {w.rh!=null?`${Math.round(w.rh)}%`:'—'}</strong><span>{w.windDir||'—'} {w.windMph!=null?`${Math.round(w.windMph)} mph`:''}</span><small>{w.sourceName||w.source}</small></div>)}</div></section>
  </div>
}
