import { useEffect, useMemo, useRef } from 'react';
import maplibregl, { type GeoJSONSource, type Map } from 'maplibre-gl';
import type { Bearing, Incident, Landmark, LightningEvent, Observation, TerrainSample, Tower, WatchItem } from '../types';
import { bearingRangeCorridor, destinationPoint, ellipsePolygon } from '../triangulation/geometry';
import { computeViewshedSegments } from '../terrain/terrain';

const fallbackStyle = {version:8 as const,sources:{osm:{type:'raster' as const,tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster' as const,source:'osm'}]};
type Props={towers:Tower[];landmarks:Landmark[];observations:Observation[];incidents:Incident[];bearings:Bearing[];watchItems:WatchItem[];lightning?:LightningEvent[];terrainSamples?:TerrainSample[];viewshedEnabled?:boolean;viewshedRangeM?:number;activeTowerId?:string;onlineMap?:boolean;focus?:{lat:number;lon:number}|null;target?:{lat:number;lon:number}|null;onMapClick?:(p:{lat:number;lon:number})=>void};

export default function FireMap({towers,landmarks,observations,incidents,bearings,watchItems,lightning=[],terrainSamples=[],viewshedEnabled=false,viewshedRangeM=30000,activeTowerId,onlineMap=true,focus,target,onMapClick}:Props){
  const el=useRef<HTMLDivElement>(null);const mapRef=useRef<Map|null>(null);const clickRef=useRef(onMapClick);clickRef.current=onMapClick;const local=towers.find(t=>t.id===activeTowerId)||towers.find(t=>t.local)||towers[0];
  const viewshed=useMemo(()=>local&&viewshedEnabled?computeViewshedSegments(local,terrainSamples,viewshedRangeM):[],[local?.id,viewshedEnabled,viewshedRangeM,terrainSamples]);
  useEffect(()=>{if(!el.current||mapRef.current||!local)return;const style=onlineMap?fallbackStyle:{version:8 as const,sources:{},layers:[{id:'bg',type:'background' as const,paint:{'background-color':'#111a16'}}]};const map=new maplibregl.Map({container:el.current,style,center:[local.lon,local.lat],zoom:10.3,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');const click=(e:any)=>clickRef.current?.({lat:e.lngLat.lat,lon:e.lngLat.lng});map.on('click',click);mapRef.current=map;return()=>{map.off('click',click);map.remove();mapRef.current=null}},[local?.id,onlineMap]);
  useEffect(()=>{const map=mapRef.current;if(!map||!local)return;const render=()=>{const points:any[]=[];const lines:any[]=[];const polygons:any[]=[];const viewLines:any[]=[];
    towers.forEach(t=>points.push({type:'Feature',properties:{kind:'tower',name:t.name,local:t.id===local.id},geometry:{type:'Point',coordinates:[t.lon,t.lat]}}));
    landmarks.forEach(l=>points.push({type:'Feature',properties:{kind:'landmark',name:l.name},geometry:{type:'Point',coordinates:[l.lon,l.lat]}}));
    lightning.filter(x=>x.status!=='CLOSED').forEach(x=>points.push({type:'Feature',properties:{kind:'lightning',name:`Lightning · ${new Date(x.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`},geometry:{type:'Point',coordinates:[x.lon,x.lat]}}));
    if(target)points.push({type:'Feature',properties:{kind:'target',name:'Terrain target'},geometry:{type:'Point',coordinates:[target.lon,target.lat]}});
    incidents.filter(i=>i.targetLat!=null&&i.targetLon!=null).forEach(i=>{points.push({type:'Feature',properties:{kind:'incident',name:i.title,status:i.status},geometry:{type:'Point',coordinates:[i.targetLon!,i.targetLat!]}});if(i.uncertaintyEllipse){const poly=ellipsePolygon({lat:i.targetLat!,lon:i.targetLon!},i.uncertaintyEllipse);polygons.push({type:'Feature',properties:{kind:'triangulation',name:i.title},geometry:{type:'Polygon',coordinates:[poly.map(p=>[p.lon,p.lat])]}})}});
    watchItems.filter(w=>w.targetLat!=null&&w.targetLon!=null&&w.status==='OPEN').forEach(w=>points.push({type:'Feature',properties:{kind:'watch',name:w.title},geometry:{type:'Point',coordinates:[w.targetLon!,w.targetLat!]}}));
    observations.forEach(o=>{const t=towers.find(x=>x.id===o.towerId);if(!t)return;const end=o.targetLat!=null&&o.targetLon!=null?{lat:o.targetLat,lon:o.targetLon}:destinationPoint(t.lat,t.lon,o.bearingDeg,Math.max(o.rangeM||30000,30000));lines.push({type:'Feature',properties:{kind:'observation',reportId:o.reportId},geometry:{type:'LineString',coordinates:[[t.lon,t.lat],[end.lon,end.lat]]}});if(o.rangeM&&(o.bearingUncertaintyDeg||o.rangeUncertaintyM)){const poly=bearingRangeCorridor(t,o.bearingDeg,o.bearingUncertaintyDeg||0.5,o.rangeM,o.rangeUncertaintyM||0);polygons.push({type:'Feature',properties:{kind:'corridor',reportId:o.reportId},geometry:{type:'Polygon',coordinates:[poly.map(p=>[p.lon,p.lat])]}})}});
    bearings.forEach(b=>{const t=towers.find(x=>x.id===b.towerId);if(!t)return;const end=destinationPoint(t.lat,t.lon,b.bearingDeg,50000);lines.push({type:'Feature',properties:{kind:'bearing',reportId:b.reportId},geometry:{type:'LineString',coordinates:[[t.lon,t.lat],[end.lon,end.lat]]}})});
    viewshed.forEach(v=>viewLines.push({type:'Feature',properties:{visible:v.visible},geometry:{type:'LineString',coordinates:[[v.from.lon,v.from.lat],[v.to.lon,v.to.lat]]}}));
    const data=(features:any[])=>({type:'FeatureCollection',features});
    if(map.getSource('fw-viewshed'))(map.getSource('fw-viewshed') as GeoJSONSource).setData(data(viewLines) as any);else{map.addSource('fw-viewshed',{type:'geojson',data:data(viewLines) as any});map.addLayer({id:'fw-viewshed',type:'line',source:'fw-viewshed',paint:{'line-color':['case',['get','visible'],'#5fae7d','#6d6251'],'line-width':3,'line-opacity':['case',['get','visible'],0.22,0.10]}})}
    if(map.getSource('fw-polygons'))(map.getSource('fw-polygons') as GeoJSONSource).setData(data(polygons) as any);else{map.addSource('fw-polygons',{type:'geojson',data:data(polygons) as any});map.addLayer({id:'fw-polygons',type:'fill',source:'fw-polygons',paint:{'fill-color':['match',['get','kind'],'triangulation','#ff6b45','#e9b75b'],'fill-opacity':['match',['get','kind'],'triangulation',0.16,0.10]}});map.addLayer({id:'fw-polygon-outline',type:'line',source:'fw-polygons',paint:{'line-color':['match',['get','kind'],'triangulation','#ff6b45','#e9b75b'],'line-width':1.4,'line-dasharray':[2,2]}})}
    if(map.getSource('fw-lines'))(map.getSource('fw-lines') as GeoJSONSource).setData(data(lines) as any);else{map.addSource('fw-lines',{type:'geojson',data:data(lines) as any});map.addLayer({id:'fw-lines',type:'line',source:'fw-lines',paint:{'line-color':'#e9b75b','line-width':2,'line-opacity':0.82,'line-dasharray':[3,2]}})}
    if(map.getSource('fw-points'))(map.getSource('fw-points') as GeoJSONSource).setData(data(points) as any);else{map.addSource('fw-points',{type:'geojson',data:data(points) as any});map.addLayer({id:'fw-points',type:'circle',source:'fw-points',paint:{'circle-radius':['match',['get','kind'],'tower',7,'incident',8,'watch',6,'lightning',4,'target',7,4],'circle-color':['match',['get','kind'],'tower','#d9e7dd','incident','#ff6b45','watch','#e4be55','lightning','#b79cff','target','#77c7d9','#93a89c'],'circle-stroke-color':'#07100c','circle-stroke-width':2}});map.addLayer({id:'fw-labels',type:'symbol',source:'fw-points',layout:{'text-field':['get','name'],'text-size':11,'text-offset':[0,1.2],'text-anchor':'top'},paint:{'text-color':'#eaf0ec','text-halo-color':'#0b120f','text-halo-width':1.5}})}
  };if(map.loaded())render();else map.once('load',render)},[towers,landmarks,observations,incidents,bearings,watchItems,lightning,viewshed,target,local]);
  useEffect(()=>{if(focus&&mapRef.current)mapRef.current.flyTo({center:[focus.lon,focus.lat],zoom:12})},[focus]);
  return <div className="map-shell"><div ref={el} className="map-canvas"/><div className="map-legend"><span><i className="dot tower"/> Tower</span><span><i className="dot fire"/> Incident</span><span><i className="dot lightning"/> Lightning</span><span><i className="line sample"/> Bearing</span>{viewshedEnabled&&<span>◫ Viewshed</span>}<span>▱ Uncertainty</span></div></div>
}
