import { db } from '../storage/db';
import type { Incident, ShiftRecord, Tower } from '../types';
import { fmtDateTime } from '../utils/time';

const line=(label:string,value:unknown)=>`${label.padEnd(20)} ${value??'-'}`;
const section=(name:string)=>`\n${name.toUpperCase()}\n${'-'.repeat(Math.min(72,name.length+8))}`;
export type BuiltReport={title:string;textBody:string;snapshot:Record<string,unknown>;incidentId?:string;shiftId?:string};

export async function buildIncidentReport(incident:Incident,tower:Tower):Promise<BuiltReport>{
  const observations=(await db.observations.where('incidentId').equals(incident.id).toArray()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  const bearings=(await db.bearings.where('incidentId').equals(incident.id).toArray()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  const radios=(await db.radioLogs.where('incidentId').equals(incident.id).toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  const logs=(await db.shiftLogs.where('incidentId').equals(incident.id).toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  const mesh=(await db.meshMessages.where('reportId').equals(incident.reportId).toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  const wxIds=[...new Set(observations.map(o=>o.weatherObservationId).filter(Boolean) as string[])];const weather=(await Promise.all(wxIds.map(id=>db.weather.get(id)))).filter(Boolean);
  const towers=await db.towers.toArray();
  const lines=[line('Tower',tower.name),line('Report ID',incident.reportId),line('Incident',incident.title),line('Generated',fmtDateTime(new Date().toISOString())),line('Status',incident.status),line('Confidence',incident.confidence),line('Urgency',incident.urgency),section('Location'),line('Latitude',incident.targetLat?.toFixed(6)),line('Longitude',incident.targetLon?.toFixed(6)),line('Method',incident.locationMethod),line('Uncertainty',incident.uncertaintyM?`+/- ${Math.round(incident.uncertaintyM)} m`:'-'),line('Geometry',incident.geometryQuality),line('RMS residual',incident.rmsResidualDeg!=null?`${incident.rmsResidualDeg.toFixed(2)} deg`:'-'),section('Bearing evidence'),...bearings.map(b=>`${fmtDateTime(b.createdAt)} | ${towers.find(t=>t.id===b.towerId)?.name||b.towerId} | ${b.bearingDeg.toFixed(1)} deg +/- ${b.uncertaintyDeg.toFixed(1)} deg`),section('Observations'),...observations.map(o=>`${fmtDateTime(o.createdAt)} | ${o.type} ${o.confidence} | ${o.bearingDeg.toFixed(1)} deg | ${o.notes||'No notes'}`),section('Weather attached to observations'),...(weather.length?weather.map(w=>`${fmtDateTime(w!.timestamp)} | ${w!.sourceName||w!.source} | ${w!.temperatureF!=null?`${Math.round(w!.temperatureF)} F`:''} RH ${w!.rh??'-'} | ${w!.windDir||'-'} ${w!.windMph??'-'} mph`):['No attached weather records.']),section('Communications'),...(radios.length?radios.map(r=>`${fmtDateTime(r.timestamp)} | ${r.direction} ${r.station} | ${r.type} | ${r.notes}`):['No incident-linked radio entries.']),section('FWP mesh evidence'),...(mesh.length?mesh.map(m=>`${fmtDateTime(m.timestamp)} | ${m.messageType} | ${m.originNode} | ${m.deliveryState} | ${m.payloadBytes??'-'} bytes`):['No associated FWP messages.']),section('Timeline'),...(logs.length?logs.map(l=>`${fmtDateTime(l.timestamp)} | ${l.kind} | ${l.message}`):['No incident timeline entries.'])];
  return {title:`FIREWATCH Incident Report - ${incident.reportId}`,textBody:lines.join('\n'),snapshot:{tower,incident,observations,bearings,weather,radios,mesh,logs},incidentId:incident.id};
}

export async function buildShiftReport(shift:ShiftRecord,tower:Tower):Promise<BuiltReport>{
  const end=shift.endedAt??new Date().toISOString();const between=<T extends {timestamp:string}>(rows:T[])=>rows.filter(r=>r.timestamp>=shift.startedAt&&r.timestamp<=end);
  const logs=between(await db.shiftLogs.toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const radios=between(await db.radioLogs.toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const weather=between(await db.weather.toArray()).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const observations=(await db.observations.toArray()).filter(o=>o.createdAt>=shift.startedAt&&o.createdAt<=end);const incidents=(await db.incidents.toArray()).filter(i=>i.updatedAt>=shift.startedAt&&i.updatedAt<=end);const maintenance=between(await db.maintenance.toArray());const runs=(await db.procedureRuns.toArray()).filter(r=>r.startedAt>=shift.startedAt&&r.startedAt<=end);
  const lines=[line('Tower',tower.name),line('Operator',shift.operatorName),line('Shift start',fmtDateTime(shift.startedAt)),line('Shift end',shift.endedAt?fmtDateTime(shift.endedAt):'ACTIVE'),line('Generated',fmtDateTime(new Date().toISOString())),section('Summary'),line('Observations',observations.length),line('Incidents touched',incidents.length),line('Radio entries',radios.length),line('Weather records',weather.length),line('Procedure runs',runs.length),line('Maintenance entries',maintenance.length),section('Weather'),...weather.map(w=>`${fmtDateTime(w.timestamp)} | ${w.temperatureF!=null?`${Math.round(w.temperatureF)} F`:'-'} | RH ${w.rh??'-'} | ${w.windDir||'-'} ${w.windMph??'-'} mph | ${w.sourceName||w.source}`),section('Observations'),...observations.map(o=>`${fmtDateTime(o.createdAt)} | ${o.reportId} | ${o.type} ${o.confidence} | ${o.bearingDeg.toFixed(1)} deg`),section('Radio'),...radios.map(r=>`${fmtDateTime(r.timestamp)} | ${r.direction} ${r.station} | ${r.type} | ${r.notes}`),section('Shift chronology'),...logs.map(l=>`${fmtDateTime(l.timestamp)} | ${l.kind} | ${l.message}`),section('Handoff notes'),shift.handoffNotes||'None'];
  return {title:`FIREWATCH Shift Report - ${shift.operatorName}`,textBody:lines.join('\n'),snapshot:{tower,shift,logs,radios,weather,observations,incidents,maintenance,runs},shiftId:shift.id};
}

export async function buildHandoffReport(shift:ShiftRecord|undefined,tower:Tower,network:{online:boolean;mesh:string}):Promise<BuiltReport>{
  const incidents=(await db.incidents.toArray()).filter(i=>i.status!=='CLOSED');const watches=(await db.watchItems.toArray()).filter(w=>w.status!=='DONE');const lightning=(await db.lightning.toArray()).filter(l=>!['CLOSED','NO SMOKE'].includes(l.status));const equipment=(await db.equipment.toArray()).filter(e=>e.status!=='OK');const weather=(await db.weather.orderBy('timestamp').reverse().first());const maintenance=(await db.maintenance.orderBy('timestamp').reverse().limit(10).toArray());
  const lines=[line('Tower',tower.name),line('Outgoing operator',shift?.operatorName||'Not recorded'),line('Generated',fmtDateTime(new Date().toISOString())),section('Operational state'),line('Active incidents',incidents.length),line('Open rechecks',watches.length),line('Lightning watches',lightning.length),line('Equipment issues',equipment.length),line('Internet / Starlink',network.online?'ONLINE':'OFFLINE'),line('Meshtastic',network.mesh),section('Priority handoff'),...(incidents.map(i=>`INCIDENT ${i.reportId} | ${i.status} | ${i.title} | ${i.targetLat?.toFixed(5)??'-'}, ${i.targetLon?.toFixed(5)??'-'}`)),...(watches.map(w=>`RECHECK ${w.priority} | ${w.title} | ${w.reason}`)),...(equipment.map(e=>`EQUIPMENT ${e.status} | ${e.name} | ${e.notes||''}`)),section('Latest weather'),weather?`${fmtDateTime(weather.timestamp)} | ${weather.temperatureF!=null?`${Math.round(weather.temperatureF)} F`:'-'} | RH ${weather.rh??'-'} | ${weather.windDir||'-'} ${weather.windMph??'-'} mph | ${weather.sourceName||weather.source}`:'No weather record.',section('Recent maintenance'),...maintenance.map(m=>`${fmtDateTime(m.timestamp)} | ${m.kind} | ${m.notes}`),section('Operator notes'),shift?.handoffNotes||'None'];
  return {title:`FIREWATCH Handoff - ${tower.name}`,textBody:lines.join('\n'),snapshot:{tower,shift,incidents,watches,lightning,equipment,weather,maintenance,network},shiftId:shift?.id};
}
