import { db } from '../storage/db';
import type { Procedure } from '../types';

export const DEFAULT_PROCEDURES:Procedure[]=[
{id:'proc-opening',category:'OPENING',title:'Opening the lookout',steps:['Inspect tower and access route for immediate hazards','Power and inspect primary radio and backup radio','Verify Meshtastic node / FIREWATCH bridge status','Inspect Fire Finder and confirm azimuth reference','Record opening weather observation','Check overnight lightning and unresolved rechecks','Complete initial horizon scan','Confirm communications check with Dispatch'],notes:'Adapt to local agency procedures.'},
{id:'proc-closing',category:'CLOSING',title:'Closing the lookout',steps:['Review active incidents and unresolved sightings','Complete final horizon scan','Record closing weather observation','Generate handoff report / enter handoff notes','Confirm radio and mesh equipment disposition','Secure optics and Fire Finder as locally required','Check battery / solar / generator state','Close or hand off current shift'],notes:'Do not use this checklist in place of local closing orders.'},
{id:'proc-radio',category:'RADIO',title:'Radio report reference',steps:['Identify station / callsign','State observation type and urgency','Provide bearing and estimated range or coordinates if available','State confidence and important smoke/fire flags','Request acknowledgment','Log the operational acknowledgment separately from radio transport delivery']},
{id:'proc-firefinder',category:'FIRE FINDER',title:'Fire Finder observation',steps:['Verify instrument reference / zero','Measure azimuth','Record bearing uncertainty','Measure vertical angle if available','Estimate range only when supported','Create FIREWATCH sighting immediately','Request cooperating lookout bearing when useful','Preserve raw measurement and derived location separately']},
{id:'proc-weather',category:'WEATHER',title:'Tower weather observation',steps:['Record temperature','Record relative humidity','Record wind direction and speed','Record gusts','Record visibility using known landmarks','Record pressure / precipitation / cloud cover when available','Verify source provenance in FIREWATCH']},
{id:'proc-lightning',category:'LIGHTNING',title:'Post-lightning visual check',steps:['Review strike clusters / watch queue','Use LOOK HERE to acquire target sector','Check terrain and horizon reference','Record CLEAR, OBSCURED, SMOKE, or FIRE','Create recheck if obscured or uncertain','Escalate smoke/fire through normal sighting workflow']},
{id:'proc-emergency',category:'EMERGENCY',title:'Emergency reference',steps:['Follow current agency emergency and incident-command procedures','Establish communications with Dispatch / designated authority','Use local evacuation / lightning / medical procedures','Preserve FIREWATCH as a supporting observation/logging tool only'],notes:'Replace or supplement with authoritative local emergency procedures before operational deployment.'},
{id:'proc-facility',category:'FACILITY',title:'Power / facility check',steps:['Inspect solar / battery state','Inspect generator state and fuel if applicable','Check Starlink / network equipment','Check tower weather sensor','Record equipment faults and maintenance notes']}
];
export async function ensureTowerDefaults(){if(await db.procedures.count()===0)await db.procedures.bulkAdd(DEFAULT_PROCEDURES)}
