import { useEffect, useMemo, useState } from 'react';
import Badge from '../components/Badge';
import WeatherWorkspace from '../weather/WeatherWorkspace';
import ReportsWorkspace from '../reports/ReportsWorkspace';
import { db, exportBackup, importBackup } from '../storage/db';
import { clearAll } from '../storage/demo';
import { useTable } from '../hooks';
import type { AppSettings, EquipmentStatus, MaintenanceEntry, Procedure, ShiftRecord, Tower } from '../types';
import { makeId } from '../utils/ids';
import { fmtDateTime } from '../utils/time';
import { ensureTowerDefaults } from './defaults';

type Tab='OVERVIEW'|'WEATHER'|'REPORTS'|'PROCEDURES'|'CONTACTS';
type Props={tower:Tower;settings:AppSettings;onSettings:(p:Partial<AppSettings>)=>void;networkOnline:boolean;bridge:any};
function dlJson(data:unknown,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function TowerWorkspace({tower,settings,onSettings,networkOnline,bridge}:Props){
  const [tab,setTab]=useState<Tab>('OVERVIEW');const equipment=useTable(db.equipment),maintenance=useTable(db.maintenance,'timestamp'),procedures=useTable(db.procedures),runs=useTable(db.procedureRuns,'startedAt'),contacts=useTable(db.contacts),shifts=useTable(db.shifts,'startedAt'),landmarks=useTable(db.landmarks),panoramas=useTable(db.panoramas),lightning=useTable(db.lightning),terrain=useTable(db.terrainSamples);
  useEffect(()=>{ensureTowerDefaults()},[]);const activeShift=shifts.find(s=>s.status==='ACTIVE');const meshState=settings.meshMode==='SIMULATED'?'SIMULATED':bridge?.snapshot?.radioConnected?'CONNECTED':bridge?.snapshot?.state||'DISCONNECTED';
  return <div className="tower-page batch3"><header className="page-header"><div><span className="section-kicker">TOWER OPERATIONS · v1.0</span><h1>{tower.name}</h1><p>{tower.callsign||'No callsign'} · {tower.lat.toFixed(5)}, {tower.lon.toFixed(5)} · {activeShift?`SHIFT: ${activeShift.operatorName}`:'NO ACTIVE SHIFT'}</p></div>{activeShift&&<Badge tone="ok">ON DUTY</Badge>}</header><div className="tower-subnav">{(['OVERVIEW','WEATHER','REPORTS','PROCEDURES','CONTACTS'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='OVERVIEW'&&<Overview tower={tower} settings={settings} onSettings={onSettings} networkOnline={networkOnline} meshState={meshState} bridge={bridge} equipment={equipment} maintenance={maintenance} shifts={shifts} panoramas={panoramas.length} lightning={lightning.length} terrain={terrain.length}/>} 
    {tab==='WEATHER'&&<WeatherWorkspace tower={tower} landmarks={landmarks} settings={settings} onSettings={onSettings}/>} 
    {tab==='REPORTS'&&<ReportsWorkspace tower={tower} networkOnline={networkOnline} meshState={meshState}/>} 
    {tab==='PROCEDURES'&&<Procedures procedures={procedures} runs={runs} activeShift={activeShift}/>} 
    {tab==='CONTACTS'&&<Contacts contacts={contacts}/>} 
  </div>
}

function Overview({tower,settings,onSettings,networkOnline,meshState,bridge,equipment,maintenance,shifts,panoramas,lightning,terrain}:{tower:Tower;settings:AppSettings;onSettings:(p:Partial<AppSettings>)=>void;networkOnline:boolean;meshState:string;bridge:any;equipment:any[];maintenance:MaintenanceEntry[];shifts:ShiftRecord[];panoramas:number;lightning:number;terrain:number}){
  const active=shifts.find(s=>s.status==='ACTIVE');const [operator,setOperator]=useState(''),[newEquipment,setNewEquipment]=useState(''),[mEq,setMEq]=useState(''),[mKind,setMKind]=useState<MaintenanceEntry['kind']>('NOTE'),[mNotes,setMNotes]=useState(''),[handoff,setHandoff]=useState(active?.handoffNotes||'');
  useEffect(()=>setHandoff(active?.handoffNotes||''),[active?.id,active?.handoffNotes]);
  async function startShift(){if(!operator.trim())return;const now=new Date().toISOString(),s:ShiftRecord={id:makeId('shift'),towerId:tower.id,operatorName:operator.trim(),startedAt:now,status:'ACTIVE'};await db.shifts.add(s);await db.shiftLogs.add({id:makeId('log'),timestamp:now,kind:'SHIFT',message:`SHIFT START — ${operator.trim()} at ${tower.name}`});setOperator('')}
  async function endShift(){if(!active)return;const now=new Date().toISOString();await db.shifts.update(active.id,{status:'CLOSED',endedAt:now,handoffNotes:handoff});await db.shiftLogs.add({id:makeId('log'),timestamp:now,kind:'SHIFT',message:`SHIFT END — ${active.operatorName}`})}
  async function addMaintenance(){if(!mEq||!mNotes.trim())return;const now=new Date().toISOString();await db.maintenance.add({id:makeId('maint'),equipmentId:mEq,timestamp:now,kind:mKind,notes:mNotes.trim()});await db.shiftLogs.add({id:makeId('log'),timestamp:now,kind:'EQUIPMENT',message:`${equipment.find(e=>e.id===mEq)?.name||mEq}: ${mKind} — ${mNotes.trim()}`});setMNotes('')}
  async function backup(){dlJson(await exportBackup(),`firewatch-backup-${new Date().toISOString().slice(0,10)}.json`)}
  async function fresh(){if(confirm('Clear all FIREWATCH station data on this browser?')){await clearAll();location.reload()}}
  return <><div className="tower-grid"><section className="panel"><span className="section-kicker">SHIFT</span><h2>{active?'Active shift':'Start shift'}</h2>{active?<><div className="fact-row"><span>Operator</span><strong>{active.operatorName}</strong></div><div className="fact-row"><span>Started</span><strong>{fmtDateTime(active.startedAt)}</strong></div><label className="setting-row stacked"><div><strong>Handoff notes</strong><small>Included in shift and handoff reports.</small></div><textarea rows={4} value={handoff} onChange={e=>setHandoff(e.target.value)} onBlur={()=>db.shifts.update(active.id,{handoffNotes:handoff})}/></label><button className="btn danger" onClick={endShift}>Close shift</button></>:<><label className="setting-row stacked"><div><strong>Operator name</strong></div><input value={operator} onChange={e=>setOperator(e.target.value)} placeholder="Lookout / operator"/></label><button className="btn primary" onClick={startShift}>Start shift</button></>}<div className="mini-history">{shifts.filter(s=>s.status==='CLOSED').slice(0,4).map(s=><div key={s.id}><strong>{s.operatorName}</strong><span>CLOSED</span><small>{fmtDateTime(s.startedAt)} → {s.endedAt?fmtDateTime(s.endedAt):'—'}</small></div>)}</div></section>
  <section className="panel"><span className="section-kicker">NETWORK</span><h2>Connectivity</h2><Status label="Local database" state="READY"/><Status label="PWA cache" state="READY"/><Status label="Meshtastic" state={meshState}/><Status label="Internet / Starlink" state={networkOnline?'LIVE':'OFFLINE'}/><Status label="Server sync" state={settings.syncEnabled?"ENABLED":"DISABLED"}/></section>
  <section className="panel"><span className="section-kicker">FIELD DATA</span><h2>Offline layers</h2><Status label="Horizon panoramas" state={String(panoramas)}/><Status label="Lightning records" state={String(lightning)}/><Status label="Terrain samples" state={String(terrain)}/><label className="setting-row"><div><strong>Viewshed range</strong></div><select value={settings.viewshedRangeM} onChange={e=>onSettings({viewshedRangeM:Number(e.target.value)})}><option value="15000">15 km</option><option value="30000">30 km</option><option value="50000">50 km</option></select></label></section>
  <section className="panel"><span className="section-kicker">EQUIPMENT</span><h2>Station systems</h2><div className="equipment-add"><input value={newEquipment} onChange={e=>setNewEquipment(e.target.value)} placeholder="Add equipment…"/><button className="btn ghost" onClick={async()=>{if(!newEquipment.trim())return;await db.equipment.add({id:makeId('eq'),name:newEquipment.trim(),status:'UNKNOWN'});setNewEquipment('')}}>Add</button></div>{equipment.map(e=><div className="equipment-row equipment-edit" key={e.id}><span>{e.name}<small>{e.notes}</small></span><select value={e.status} onChange={async ev=>{const status=ev.target.value as EquipmentStatus;await db.equipment.update(e.id,{status});await db.shiftLogs.add({id:makeId('log'),timestamp:new Date().toISOString(),kind:'EQUIPMENT',message:`${e.name} status changed to ${status}`})}}>{['OK','WATCH','FAULT','OUT OF SERVICE','UNKNOWN'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section>
  <section className="panel"><span className="section-kicker">MAINTENANCE LOG</span><h2>Equipment evidence</h2><div className="maintenance-form"><select value={mEq} onChange={e=>setMEq(e.target.value)}><option value="">Equipment…</option>{equipment.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select value={mKind} onChange={e=>setMKind(e.target.value as MaintenanceEntry['kind'])}>{['INSPECTION','FAULT','SERVICE','NOTE'].map(k=><option key={k}>{k}</option>)}</select><input value={mNotes} onChange={e=>setMNotes(e.target.value)} placeholder="Maintenance note"/><button className="btn secondary" onClick={addMaintenance}>Log</button></div><div className="mini-history">{maintenance.slice(0,8).map(m=><div key={m.id}><strong>{equipment.find(e=>e.id===m.equipmentId)?.name||m.equipmentId}</strong><span>{m.kind}</span><small>{fmtDateTime(m.timestamp)} · {m.notes}</small></div>)}</div></section>
  <section className="panel"><span className="section-kicker">LOCAL BEHAVIOR</span><h2>Settings</h2><label className="setting-row"><div><strong>Online map tiles</strong><small>Operational records stay local.</small></div><input type="checkbox" checked={settings.onlineMapEnabled} onChange={e=>onSettings({onlineMapEnabled:e.target.checked})}/></label><label className="setting-row"><div><strong>Weather auto poll</strong></div><input type="checkbox" checked={settings.weatherAutoPoll} onChange={e=>onSettings({weatherAutoPoll:e.target.checked})}/></label><label className="setting-row"><div><strong>Mesh heartbeat</strong></div><select value={settings.heartbeatMinutes} onChange={e=>onSettings({heartbeatMinutes:Number(e.target.value) as 0|15|30|60})}><option value="0">Disabled</option><option value="15">15 min</option><option value="30">30 min</option><option value="60">60 min</option></select></label></section>
  <section className="panel"><span className="section-kicker">MESHTASTIC BRIDGE</span><h2>Radio transport</h2><label className="setting-row stacked"><div><strong>Transport mode</strong></div><select value={settings.meshMode} onChange={e=>onSettings({meshMode:e.target.value as AppSettings['meshMode']})}><option value="SIMULATED">Simulated</option><option value="BRIDGE">Local radio bridge</option></select></label><label className="setting-row stacked"><div><strong>Bridge WebSocket</strong></div><input value={settings.bridgeUrl} onChange={e=>onSettings({bridgeUrl:e.target.value})}/></label><label className="setting-row stacked"><div><strong>FWP private port</strong></div><input type="number" min="256" max="511" value={settings.fwpPortNum} onChange={e=>onSettings({fwpPortNum:Math.max(256,Math.min(511,Number(e.target.value)||256))})}/></label><div className="bridge-readout"><strong>{bridge?.snapshot?.state||'DISCONNECTED'}</strong><span>{bridge?.snapshot?.error||`${bridge?.snapshot?.nodes?.length||0} known mesh nodes`}</span></div></section>
  <section className="panel"><span className="section-kicker">DATA</span><h2>Station backup</h2><div className="stack-actions"><button className="btn secondary" onClick={backup}>Export FIREWATCH backup</button><label className="btn secondary file-btn">Import backup<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f){await importBackup(JSON.parse(await f.text()));location.reload()}}}/></label><button className="btn danger" onClick={fresh}>Fresh start / clear data</button></div></section></div><section className="disclaimer"><strong>Operational boundary</strong><p>FIREWATCH supports observation, communications, mapping, coordination, and evidence generation. It does not replace agency procedures, incident command, official weather products, evacuation decisions, or validated wildfire systems.</p></section></>
}
function Status({label,state}:{label:string;state:string}){return <div className="status-line"><span>{label}</span><strong>{state}</strong></div>}

function Procedures({procedures,runs,activeShift}:{procedures:Procedure[];runs:any[];activeShift?:ShiftRecord}){
  const [selected,setSelected]=useState<Procedure|undefined>(procedures[0]);useEffect(()=>{if(!selected&&procedures[0])setSelected(procedures[0])},[procedures.length]);const run=selected?runs.find(r=>r.procedureId===selected.id&&!r.completedAt):undefined;
  async function ensureRun(){if(!selected)return undefined;if(run)return run;const row={id:makeId('prun'),procedureId:selected.id,shiftId:activeShift?.id,startedAt:new Date().toISOString(),completedSteps:[]};await db.procedureRuns.add(row);return row}
  async function toggle(i:number){const r=await ensureRun();if(!r)return;const current:number[]=r.completedSteps||[];const next=current.includes(i)?current.filter(x=>x!==i):[...current,i].sort((a,b)=>a-b);await db.procedureRuns.update(r.id,{completedSteps:next})}
  async function complete(){const r=await ensureRun();if(!r||!selected)return;const now=new Date().toISOString();await db.procedureRuns.update(r.id,{completedAt:now,completedSteps:selected.steps.map((_,i)=>i)});await db.shiftLogs.add({id:makeId('log'),timestamp:now,kind:'PROCEDURE',message:`Completed checklist: ${selected.title}`})}
  return <div className="procedure-layout"><aside className="procedure-list">{procedures.map(p=><button key={p.id} className={selected?.id===p.id?'active':''} onClick={()=>setSelected(p)}><span>{p.category}</span><strong>{p.title}</strong></button>)}</aside><section className="procedure-detail">{selected?<><span className="section-kicker">{selected.category}</span><h2>{selected.title}</h2>{selected.notes&&<p className="instrument-help">{selected.notes}</p>}<div className="checklist">{selected.steps.map((step,i)=><label key={i}><input type="checkbox" checked={!!run?.completedSteps?.includes(i)} onChange={()=>toggle(i)}/><span>{step}</span></label>)}</div><button className="btn primary" onClick={complete}>Complete checklist</button><div className="mini-history">{runs.filter(r=>r.procedureId===selected.id).slice(0,6).map(r=><div key={r.id}><strong>{r.completedAt?'COMPLETE':'IN PROGRESS'}</strong><small>{fmtDateTime(r.startedAt)}{r.completedAt?` → ${fmtDateTime(r.completedAt)}`:''}</small></div>)}</div></>:<p>No procedures configured.</p>}</section></div>
}
function Contacts({contacts}:{contacts:any[]}){const [name,setName]=useState(''),[role,setRole]=useState(''),[callsign,setCallsign]=useState(''),[phone,setPhone]=useState(''),[channel,setChannel]=useState('');async function add(){if(!name.trim())return;await db.contacts.add({id:makeId('contact'),name:name.trim(),role:role||'Contact',callsign:callsign||undefined,phone:phone||undefined,radioChannel:channel||undefined});setName('');setRole('');setCallsign('');setPhone('');setChannel('')}return <div className="contacts-workspace"><div className="panel-header"><div><span className="section-kicker">OFFLINE DIRECTORY</span><h2>Contacts and stations</h2></div></div><div className="contact-add"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name / station"/><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Role"/><input value={callsign} onChange={e=>setCallsign(e.target.value)} placeholder="Callsign"/><input value={channel} onChange={e=>setChannel(e.target.value)} placeholder="Radio channel"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/><button className="btn primary" onClick={add}>Add contact</button></div><div className="contact-grid">{contacts.map(c=><div className="contact-card" key={c.id}><strong>{c.name}</strong><span>{c.role}</span><small>{c.callsign||'No callsign'} · {c.radioChannel||'No channel'}</small><small>{c.phone||''}</small><button className="btn ghost" onClick={()=>db.contacts.delete(c.id)}>Remove</button></div>)}</div></div>}
