import { useMemo, useState } from 'react';
import type { TerrainSample, Tower } from '../types';
import { db } from '../storage/db';
import { lineOfSight, sampleElevation, terrainIntersection } from './terrain';
import { parseTerrainData } from './import';

export default function TerrainPanel({tower,samples,target,onTarget,viewshedEnabled,onViewshed}:{tower:Tower;samples:TerrainSample[];target?:{lat:number;lon:number}|null;onTarget:(p:{lat:number;lon:number})=>void;viewshedEnabled:boolean;onViewshed:(v:boolean)=>void}){
  const [lat,setLat]=useState(target?.lat?.toFixed(5)||'');const [lon,setLon]=useState(target?.lon?.toFixed(5)||'');const [bearing,setBearing]=useState('108.5');const [vertical,setVertical]=useState('-0.4');const [error,setError]=useState('');
  const activeTarget=target||((Number.isFinite(Number(lat))&&Number.isFinite(Number(lon)))?{lat:Number(lat),lon:Number(lon)}:null);
  const los=useMemo(()=>activeTarget?lineOfSight(tower,activeTarget,samples):null,[tower,activeTarget?.lat,activeTarget?.lon,samples]);
  const intersection=useMemo(()=>terrainIntersection(tower,Number(bearing),Number(vertical),samples),[tower,bearing,vertical,samples]);
  async function importData(file:File){try{const rows=parseTerrainData(await file.text(),file.name);if(!rows.length)throw new Error('No valid elevation samples found');await db.terrainSamples.bulkAdd(rows);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  return <section className="instrument-panel terrain-panel"><div className="section-kicker">TERRAIN / VIEWSHED · v0.6</div><h2>Modeled line of sight</h2><p className="instrument-help">Uses offline point-sampled elevation data. Results are modeled visibility, not guaranteed real-world visibility. Click the map while this tool is open or enter a target.</p>
    <div className="terrain-summary"><div><span>DEM SAMPLES</span><strong>{samples.length}</strong></div><label className="btn secondary file-btn">Import DEM / CSV / GeoJSON<input type="file" accept=".asc,.csv,.geojson,.json,text/plain,text/csv,application/geo+json,application/json" onChange={e=>e.target.files?.[0]&&importData(e.target.files[0])}/></label></div>{error&&<div className="inline-error">{error}</div>}
    <div className="form-grid"><label><span>Target latitude</span><input value={lat} onChange={e=>setLat(e.target.value)}/></label><label><span>Target longitude</span><input value={lon} onChange={e=>setLon(e.target.value)}/></label></div><button className="btn secondary wide" onClick={()=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lon))&&onTarget({lat:Number(lat),lon:Number(lon)})}>Set map target</button>
    {los&&<div className={`los-result ${los.modeled&&los.visible?'visible':'masked'}`}><span>VISIBLE FROM TOWER?</span><strong>{!los.modeled?'NO TERRAIN DATA':los.visible?'YES · MODELED':'NO · MODELED'}</strong><small>{los.bearingDeg.toFixed(1)}° · {(los.distanceM/1609.344).toFixed(2)} mi{los.targetElevationM!=null?` · ground ${Math.round(los.targetElevationM)} m`:''}</small>{los.obstruction&&<small>Obstruction ≈ {(los.obstruction.distanceM/1609.344).toFixed(2)} mi · {Math.round(los.obstruction.elevationM)} m</small>}</div>}
    <div className="terrain-intersection"><span className="mini-label">FIRE FINDER TERRAIN INTERSECTION</span><div className="form-grid"><label><span>Bearing</span><div className="input-suffix"><input value={bearing} onChange={e=>setBearing(e.target.value)}/><b>°</b></div></label><label><span>Vertical angle</span><div className="input-suffix"><input value={vertical} onChange={e=>setVertical(e.target.value)}/><b>°</b></div></label></div>{intersection?<button className="terrain-candidate" onClick={()=>onTarget({lat:intersection.lat,lon:intersection.lon})}><strong>{(intersection.distanceM/1609.344).toFixed(2)} mi</strong><span>{intersection.lat.toFixed(5)}, {intersection.lon.toFixed(5)}</span><small>terrain {Math.round(intersection.elevationM)} m · Δ {intersection.deltaDeg.toFixed(2)}°</small></button>:<div className="empty">No terrain intersection within model tolerance.</div>}</div>
    <label className="setting-row"><div><strong>Viewshed overlay</strong><small>Coarse radial model for situational awareness.</small></div><input type="checkbox" checked={viewshedEnabled} onChange={e=>onViewshed(e.target.checked)}/></label>
  </section>
}
