import { db } from './db';
import type { AppSettings, Bearing, Equipment, FWPMessage, HorizonAnnotation, HorizonPanorama, Incident, Landmark, LightningEvent, MaintenanceEntry, Observation, Sector, ShiftLogEntry, ShiftRecord, TerrainSample, Tower, TowerContact, VisibilityObservation, WatchItem, WeatherObservation, WeatherSourceConfig } from '../types';
import { DEFAULT_PROCEDURES } from '../tower/defaults';
import { bearingBetween, destinationPoint, haversineM, intersectBearings } from '../triangulation/geometry';
import { flagsToWord, encodeFWP } from '../protocol/fwp';

const minutesBefore = (m:number) => new Date(Date.now()-m*60000).toISOString();
export async function clearAll(){await db.transaction('rw',db.tables,async()=>Promise.all(db.tables.map(t=>t.clear())))}

function demoTerrain(center:{lat:number;lon:number}):TerrainSample[]{
  const out:TerrainSample[]=[];let n=0;
  for(let y=-8;y<=8;y++)for(let x=-10;x<=10;x++){
    const lat=center.lat+y*0.018,lon=center.lon+x*0.018;
    const ridge=220*Math.exp(-((x-2)**2)/12)+150*Math.exp(-((x+5)**2+(y-3)**2)/18)+90*Math.sin((x+y)/2.8);
    const base=460+35*y+ridge;
    out.push({id:`dem-${n++}`,lat,lon,elevationM:Math.round(Math.max(220,base)),source:'DEMO'});
  }
  return out;
}

export async function loadDemo(){
  await clearAll();
  const towers:Tower[]=[
    {id:'tower-black',name:'Black Ridge Lookout',lat:39.6427,lon:-78.7560,elevationM:885,timezone:'America/New_York',callsign:'BLACK RIDGE',meshtasticNodeId:'!a72f91',local:true},
    {id:'tower-pine',name:'Pine Ridge Lookout',lat:39.5755,lon:-78.5640,elevationM:806,timezone:'America/New_York',callsign:'PINE RIDGE',meshtasticNodeId:'!b119c2'},
    {id:'tower-eagle',name:'Eagle Peak Lookout',lat:39.7260,lon:-78.6080,elevationM:930,timezone:'America/New_York',callsign:'EAGLE PEAK',meshtasticNodeId:'!c813ef'}
  ];
  const target=destinationPoint(towers[0].lat,towers[0].lon,108.5,16200);const bearing2=bearingBetween(towers[1],target);
  const obs:Observation={id:'obs-a72f91',reportId:'A72F91',createdAt:minutesBefore(22),updatedAt:minutesBefore(8),towerId:'tower-black',type:'SMOKE',confidence:'HIGH',urgency:'IMPORTANT',bearingDeg:108.5,bearingUncertaintyDeg:0.4,verticalAngleDeg:-0.4,verticalAngleUncertaintyDeg:0.2,rangeM:16200,rangeUncertaintyM:900,targetLat:target.lat,targetLon:target.lon,targetMethod:'BEARING/RANGE',uncertaintyM:1100,smokeColor:'Gray',smokeDensity:'Moderate',smokeShape:'Column',notes:'Thin column above the Bear Creek drainage; growth apparent over last ten minutes.',flags:{smokeVisible:true,growing:true,column:true},incidentId:'inc-a72f91',source:'LOCAL'};
  const bearings:Bearing[]=[{id:'bear-a',reportId:'A72F91',incidentId:'inc-a72f91',towerId:'tower-black',bearingDeg:108.5,uncertaintyDeg:0.4,createdAt:minutesBefore(22),source:'LOCAL'},{id:'bear-b',reportId:'A72F91',incidentId:'inc-a72f91',towerId:'tower-pine',bearingDeg:bearing2,uncertaintyDeg:0.5,createdAt:minutesBefore(11),source:'REMOTE'}];
  const tri=intersectBearings(towers[0],108.5,towers[1],bearing2);const incident:Incident={id:'inc-a72f91',reportId:'A72F91',title:'Bear Creek smoke',status:'REPORTED',createdAt:minutesBefore(22),updatedAt:minutesBefore(8),targetLat:tri?.lat??target.lat,targetLon:tri?.lon??target.lon,uncertaintyM:tri?.uncertaintyM??1100,locationMethod:'TRIANGULATION',confidence:'HIGH',urgency:'IMPORTANT',observationIds:[obs.id],bearingIds:bearings.map(b=>b.id)};
  const landmarks:Landmark[]=[{id:'lm-bear',name:'Bear Creek',lat:39.619,lon:-78.603,type:'WATER'},{id:'lm-pine',name:'Pine Mountain',lat:39.691,lon:-78.670,type:'PEAK'},{id:'lm-road',name:'Forest Road 12',lat:39.610,lon:-78.650,type:'ROAD'},{id:'lm-radio',name:'West Ridge Repeater',lat:39.667,lon:-78.715,type:'TOWER'}];
  const sectors:Sector[]=Array.from({length:12},(_,i)=>({id:`sector-${i}`,startDeg:i*30,endDeg:(i+1)*30,lastScannedAt:minutesBefore([8,10,12,14,16,18,21,33,37,14,9,6][i])}));
  const watchItems:WatchItem[]=[{id:'watch-fire',title:'Bear Creek smoke',priority:'HIGH',reason:'Recheck growth and base visibility',dueAt:minutesBefore(-5),targetBearing:108.5,targetLat:target.lat,targetLon:target.lon,incidentId:'inc-a72f91',status:'OPEN'},{id:'watch-lightning',title:'South Fork lightning cluster',priority:'HIGH',reason:'12 strikes yesterday; no visual clear yet',targetBearing:151,targetLat:39.52,targetLon:-78.63,status:'OPEN'},{id:'watch-haze',title:'West sector haze',priority:'MEDIUM',reason:'Recheck when visibility improves',targetBearing:272,status:'OPEN'}];
  const weather:WeatherObservation[]=[{id:'wx-now',timestamp:minutesBefore(4),temperatureF:86,rh:19,windDir:'SW',windMph:13,gustMph:21,pressureInHg:29.88,precipIn:0,visibilityMi:31,cloudCover:'FEW',source:'TOWER SENSOR',sourceName:'Black Ridge local sensor',receivedAt:minutesBefore(4),staleAfterMinutes:30}];
  obs.weatherObservationId='wx-now';
  const weatherSources:WeatherSourceConfig[]=[{id:'wxsrc-local',name:'Black Ridge local sensor',kind:'LOCAL SENSOR',url:'http://127.0.0.1:8780/weather',enabled:false,pollMinutes:5,staleAfterMinutes:30}];
  const visibility:VisibilityObservation[]=landmarks.map((l,i)=>({id:`vis-${i}`,timestamp:minutesBefore(12+i),landmarkId:l.id,visible:i<3,distanceMi:haversineM(towers[0],l)/1609.344}));
  const equipment:Equipment[]=[{id:'eq-firefinder',name:'Fire Finder',status:'OK'},{id:'eq-bino',name:'Binoculars',status:'OK'},{id:'eq-wx',name:'Weather Station',status:'WATCH',notes:'Wind vane occasional dropouts'},{id:'eq-radioa',name:'Radio A',status:'OK'},{id:'eq-radiob',name:'Radio B',status:'FAULT',notes:'RX intermittent'},{id:'eq-solar',name:'Solar System',status:'OK'},{id:'eq-starlink',name:'Starlink',status:'WATCH',notes:'Intermittent'},{id:'eq-mesh',name:'Meshtastic Node',status:'OK'}];
  const logs:ShiftLogEntry[]=[{id:'log1',timestamp:minutesBefore(480),kind:'SHIFT',message:'SHIFT START — Black Ridge Lookout'},{id:'log2',timestamp:minutesBefore(462),kind:'RADIO',message:'Radio check complete with Dispatch'},{id:'log3',timestamp:minutesBefore(302),kind:'SCAN',message:'Full horizon scan complete'},{id:'log4',timestamp:minutesBefore(22),kind:'OBSERVATION',message:'Smoke observed at 108.5° — report A72F91',incidentId:'inc-a72f91'},{id:'log5',timestamp:minutesBefore(18),kind:'RADIO',message:'Dispatch notified of smoke report A72F91',incidentId:'inc-a72f91'},{id:'log6',timestamp:minutesBefore(11),kind:'MESH',message:`Remote bearing received from Pine Ridge (${bearing2.toFixed(1)}°)`,incidentId:'inc-a72f91'},{id:'log7',timestamp:minutesBefore(10),kind:'ANALYSIS',message:'Location triangulated from Black Ridge + Pine Ridge',incidentId:'inc-a72f91'}];
  const baseMsg:FWPMessage={id:'mesh-obs',version:1,messageType:'OBS',reportId:'A72F91',revision:1,timestamp:minutesBefore(22),originNode:'BLACKRIDGE',targetLat:target.lat,targetLon:target.lon,bearingDeg:108.5,rangeM:16200,eventType:'SMOKE',confidence:'HIGH',urgency:'IMPORTANT',flags:flagsToWord(obs.flags),transport:'SIMULATED',deliveryState:'DELIVERED'};let enc=encodeFWP(baseMsg);baseMsg.payloadHex=enc.hex;baseMsg.payloadBytes=enc.bytes.length;const mesh:FWPMessage[]=[baseMsg,{...baseMsg,id:'mesh-bearing',messageType:'BEARING',revision:2,timestamp:minutesBefore(11),originNode:'PINERIDGE',bearingDeg:bearing2,rangeM:0,flags:0,payloadHex:undefined,payloadBytes:undefined}];for(const m of mesh){enc=encodeFWP(m);m.payloadHex=enc.hex;m.payloadBytes=enc.bytes.length}
  const panorama:HorizonPanorama={id:'pano-main',towerId:'tower-black',name:'Primary horizon',startBearingDeg:0,spanDeg:360,createdAt:minutesBefore(1440),notes:'Demo calibration; upload a real 360° tower panorama to replace.'};
  const annotations:HorizonAnnotation[]=landmarks.map((l,i)=>({id:`ann-${i}`,panoramaId:panorama.id,landmarkId:l.id,name:l.name,bearingDeg:bearingBetween(towers[0],l)}));
  const lightning:LightningEvent[]=Array.from({length:12},(_,i)=>({id:`strike-${i}`,timestamp:minutesBefore(1100-i*3),lat:39.520+(i%4)*0.006,lon:-78.630+Math.floor(i/4)*0.006,amplitudeKa:-18-i,source:'REMOTE' as const,clusterId:'south-fork',status:'UNCHECKED' as const}));
  const terrain=demoTerrain(towers[0]);
  const shifts:ShiftRecord[]=[{id:'shift-demo',towerId:'tower-black',operatorName:'A. Lookout',startedAt:minutesBefore(480),status:'ACTIVE',handoffNotes:'Continue monitoring Bear Creek smoke. Recheck south lightning cluster if haze clears.'}];
  const maintenance:MaintenanceEntry[]=[{id:'maint-1',equipmentId:'eq-wx',timestamp:minutesBefore(95),kind:'NOTE',notes:'Wind vane dropped two samples during gusts; monitoring.'},{id:'maint-2',equipmentId:'eq-radiob',timestamp:minutesBefore(70),kind:'FAULT',notes:'Backup Radio B intermittent receive audio.'}];
  const contacts:TowerContact[]=[{id:'contact-dispatch',name:'District Dispatch',role:'Dispatch',callsign:'DISPATCH',radioChannel:'COMMAND 1'},{id:'contact-pine',name:'Pine Ridge Lookout',role:'Cooperating lookout',callsign:'PINE RIDGE',radioChannel:'LOOKOUT'},{id:'contact-engine17',name:'Engine 17',role:'Field crew',callsign:'ENGINE 17',radioChannel:'TACTICAL 2'}];
  const settings:AppSettings={id:'settings',version:'1.0.0',mode:'OPERATE',activeTowerId:'tower-black',demoLoaded:true,onlineMapEnabled:true,heartbeatMinutes:30,meshMode:'SIMULATED',bridgeUrl:'ws://127.0.0.1:8765',fwpPortNum:256,viewshedEnabled:true,viewshedRangeM:30000,activePanoramaId:panorama.id,weatherAutoPoll:true,stationRole:'LOOKOUT',stationId:'tower-black',syncEnabled:false,syncServerUrl:'http://127.0.0.1:8790',syncIntervalSeconds:60,sharePresence:true,fieldPositionMode:'MANUAL'};
  await db.transaction('rw',db.tables,async()=>{await db.towers.bulkAdd(towers);await db.landmarks.bulkAdd(landmarks);await db.observations.add(obs);await db.bearings.bulkAdd(bearings);await db.incidents.add(incident);await db.watchItems.bulkAdd(watchItems);await db.weather.bulkAdd(weather);await db.weatherSources.bulkAdd(weatherSources);await db.visibilityObservations.bulkAdd(visibility);await db.sectors.bulkAdd(sectors);await db.equipment.bulkAdd(equipment);await db.shiftLogs.bulkAdd(logs);await db.shifts.bulkAdd(shifts);await db.maintenance.bulkAdd(maintenance);await db.procedures.bulkAdd(DEFAULT_PROCEDURES);await db.contacts.bulkAdd(contacts);await db.meshMessages.bulkAdd(mesh);await db.panoramas.add(panorama);await db.horizonAnnotations.bulkAdd(annotations);await db.lightning.bulkAdd(lightning);await db.terrainSamples.bulkAdd(terrain);await db.settings.add(settings)});
}
