import { useEffect, useMemo, useState } from 'react';
import Badge from '../components/Badge';
import { useTable } from '../hooks';
import { db } from '../storage/db';
import type { AppSettings, FieldUpdate, FieldUpdateType, Incident, StationRole, SyncConflict, Tower } from '../types';
import { syncNow, pingSync } from '../sync/client';
import { makeId } from '../utils/ids';
import { fmtDateTime } from '../utils/time';
import { bearingBetween, haversineM } from '../triangulation/geometry';

type Props={tower:Tower;settings:AppSettings;onSettings:(p:Partial<AppSettings>)=>void;incidents:Incident[];networkOnline:boolean};
export default function NetworkWorkspace({tower,settings,onSettings,incidents,networkOnline}:Props){
 const updates=useTable(db.fieldUpdates,'timestamp'),presence=useTable(db.stationPresence,'timestamp'),conflicts=useTable(db.syncConflicts,'detectedAt'),statusRows=useTable(db.syncStatus);const status=statusRows[0];
 const [health,setHealth]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState<'SYNC'|'FIELD'|'DISPATCH'|'CONFLICTS'|'DIAGNOSTICS'>('SYNC');
 const open=incidents.filter(i=>i.status!=='CLOSED');
 async function run(){setBusy(true);setError('');try{await syncNow(settings);setHealth(await pingSync(settings.syncServerUrl))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function resolve(c:SyncConflict,side:'LOCAL'|'REMOTE'){if(side==='REMOTE'){const remote=JSON.parse(c.remoteJson);switch(c.entityType){case'INCIDENT':await db.incidents.put(remote);break;case'OBSERVATION':await db.observations.put(remote);break;case'BEARING':await db.bearings.put(remote);break;case'WATCH_ITEM':await db.watchItems.put(remote);break;case'RADIO_LOG':await db.radioLogs.put(remote);break;case'SHIFT_LOG':await db.shiftLogs.put(remote);break;case'FIELD_UPDATE':await db.fieldUpdates.put({...remote,source:'REMOTE'});break;case'PRESENCE':await db.stationPresence.put(remote);break;}}await db.syncConflicts.update(c.id,{status:side==='LOCAL'?'RESOLVED_LOCAL':'RESOLVED_REMOTE'})}
 return <div className="network-page"><header className="page-header"><div><span className="section-kicker">MULTI-STATION · v1.0</span><h1>Network & Field Operations</h1><p>{settings.stationRole} · station {settings.stationId} · local operation remains authoritative when links fail.</p></div><Badge tone={settings.syncEnabled?(status?.consecutiveFailures?'watch':'ok'):'info'}>{settings.syncEnabled?'SYNC ENABLED':'LOCAL ONLY'}</Badge></header>
 <div className="tower-subnav">{(['SYNC','FIELD','DISPATCH','CONFLICTS','DIAGNOSTICS'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='CONFLICTS'&&conflicts.filter(c=>c.status==='OPEN').length?` (${conflicts.filter(c=>c.status==='OPEN').length})`:''}</button>)}</div>
 {tab==='SYNC'&&<section className="network-grid"><div className="panel"><span className="section-kicker">STATION IDENTITY</span><h2>Role & replication</h2><label className="setting-row stacked"><div><strong>Station role</strong></div><select value={settings.stationRole} onChange={e=>onSettings({stationRole:e.target.value as StationRole})}>{['LOOKOUT','DISPATCH','FIELD_CREW','RANGER_STATION'].map(x=><option key={x}>{x}</option>)}</select></label><label className="setting-row stacked"><div><strong>Station ID</strong><small>Stable identity used for sync provenance.</small></div><input value={settings.stationId} onChange={e=>onSettings({stationId:e.target.value.trim()||tower.id})}/></label><label className="setting-row"><div><strong>Internet synchronization</strong><small>Optional; never required for local operation.</small></div><input type="checkbox" checked={settings.syncEnabled} onChange={e=>onSettings({syncEnabled:e.target.checked})}/></label><label className="setting-row"><div><strong>Share station presence</strong></div><input type="checkbox" checked={settings.sharePresence} onChange={e=>onSettings({sharePresence:e.target.checked})}/></label></div>
 <div className="panel"><span className="section-kicker">SERVER</span><h2>Optional Internet/LAN transport</h2><label className="setting-row stacked"><div><strong>Sync server URL</strong></div><input value={settings.syncServerUrl} onChange={e=>onSettings({syncServerUrl:e.target.value})}/></label><label className="setting-row stacked"><div><strong>Cadence</strong></div><select value={settings.syncIntervalSeconds} onChange={e=>onSettings({syncIntervalSeconds:Number(e.target.value) as AppSettings['syncIntervalSeconds']})}><option value="30">30 sec</option><option value="60">60 sec</option><option value="120">2 min</option><option value="300">5 min</option></select></label><button className="btn primary" disabled={busy||!networkOnline} onClick={run}>{busy?'Synchronizing…':'Sync now'}</button>{error&&<div className="inline-error">{error}</div>}</div>
 <div className="panel"><span className="section-kicker">SYNC STATE</span><h2>Store & forward</h2><Fact l="Cursor" v={String(status?.cursor??0)}/><Fact l="Last success" v={status?.lastSuccessAt?fmtDateTime(status.lastSuccessAt):'NEVER'}/><Fact l="Last push" v={String(status?.pushedRecords??0)}/><Fact l="Last pull" v={String(status?.pulledRecords??0)}/><Fact l="Failures" v={String(status?.consecutiveFailures??0)}/><Fact l="Server" v={health?.ok?`READY · ${health.events} events`:'UNKNOWN'}/></div>
 <div className="panel"><span className="section-kicker">REMOTE PRESENCE</span><h2>{presence.length} stations seen</h2>{presence.length?presence.slice(0,12).map(p=><div className="presence-row" key={p.id}><div><strong>{p.stationName}</strong><span>{p.role}</span></div><small>{fmtDateTime(p.timestamp)}</small></div>):<p className="muted">No remote presence records have been synchronized yet.</p>}</div></section>}
 {tab==='FIELD'&&<FieldPanel tower={tower} settings={settings} incidents={open} updates={updates}/>} 
 {tab==='DISPATCH'&&<DispatchPanel incidents={open} updates={updates} presence={presence}/>} 
 {tab==='CONFLICTS'&&<ConflictPanel conflicts={conflicts} onResolve={resolve}/>} 
 {tab==='DIAGNOSTICS'&&<Diagnostics settings={settings} networkOnline={networkOnline} health={health} conflicts={conflicts} updates={updates}/>} 
 </div>
}
function Fact({l,v}:{l:string;v:string}){return <div className="fact-row"><span>{l}</span><strong>{v}</strong></div>}
function FieldPanel({tower,settings,incidents,updates}:{tower:Tower;settings:AppSettings;incidents:Incident[];updates:FieldUpdate[]}){const [selected,setSelected]=useState(incidents[0]?.id||''),[notes,setNotes]=useState(''),[lat,setLat]=useState(String(tower.lat)),[lon,setLon]=useState(String(tower.lon)),[accuracy,setAccuracy]=useState('');useEffect(()=>{if(!selected&&incidents[0])setSelected(incidents[0].id)},[incidents,selected]);const inc=incidents.find(i=>i.id===selected);
 function device(){if(!navigator.geolocation)return; navigator.geolocation.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLon(String(p.coords.longitude));setAccuracy(String(Math.round(p.coords.accuracy)))},()=>{}, {enableHighAccuracy:true,timeout:10000})}
 async function send(type:FieldUpdateType){if(!inc)return;const now=new Date().toISOString();const u:FieldUpdate={id:makeId('field'),incidentId:inc.id,reportId:inc.reportId,timestamp:now,stationId:settings.stationId,stationName:tower.name,role:settings.stationRole,type,notes:notes.trim()||undefined,lat:Number.isFinite(Number(lat))?Number(lat):undefined,lon:Number.isFinite(Number(lon))?Number(lon):undefined,accuracyM:Number.isFinite(Number(accuracy))?Number(accuracy):undefined,source:'LOCAL'};await db.fieldUpdates.add(u);await db.shiftLogs.add({id:makeId('log'),timestamp:now,kind:'FIELD',message:`${type} — ${inc.reportId}${u.notes?` · ${u.notes}`:''}`,incidentId:inc.id});if(type==='CORRECT_LOCATION'&&u.lat!=null&&u.lon!=null)await db.incidents.update(inc.id,{targetLat:u.lat,targetLon:u.lon,locationMethod:'FIELD CREW',updatedAt:now});setNotes('')}
 const distance=inc?.targetLat!=null&&inc?.targetLon!=null?haversineM({lat:Number(lat)||tower.lat,lon:Number(lon)||tower.lon},{lat:inc.targetLat,lon:inc.targetLon}):undefined;const bearing=inc?.targetLat!=null&&inc?.targetLon!=null?bearingBetween({lat:Number(lat)||tower.lat,lon:Number(lon)||tower.lon},{lat:inc.targetLat,lon:inc.targetLon}):undefined;
 return <div className="field-layout"><section className="field-hero panel"><span className="section-kicker">FIELD CREW MODE</span><h2>{inc?.title||'No active incident'}</h2>{inc&&<><div className="field-nav"><div><span>REPORT</span><strong>{inc.reportId}</strong></div><div><span>BEARING</span><strong>{bearing!=null?`${bearing.toFixed(0)}°`:'—'}</strong></div><div><span>DISTANCE</span><strong>{distance!=null?`${(distance/1609.344).toFixed(1)} mi`:'—'}</strong></div></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{incidents.map(i=><option value={i.id} key={i.id}>{i.reportId} · {i.title}</option>)}</select><div className="field-position"><input value={lat} onChange={e=>setLat(e.target.value)} placeholder="Latitude"/><input value={lon} onChange={e=>setLon(e.target.value)} placeholder="Longitude"/><input value={accuracy} onChange={e=>setAccuracy(e.target.value)} placeholder="± m"/><button className="btn secondary" onClick={device}>Use device GPS</button></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Field update note…"/><div className="field-actions"><button onClick={()=>send('ON_SCENE')}>ON SCENE</button><button onClick={()=>send('FIRE_LOCATED')} className="alert">FIRE LOCATED</button><button onClick={()=>send('NO_FIRE_FOUND')}>NO FIRE FOUND</button><button onClick={()=>send('CORRECT_LOCATION')} className="danger">CORRECT LOCATION</button><button onClick={()=>send('STATUS')}>SEND UPDATE</button></div></>}</section><section className="panel"><span className="section-kicker">FIELD TIMELINE</span><h2>Recent updates</h2>{updates.filter(u=>!inc||u.incidentId===inc.id).slice(0,20).map(u=><div className="field-update" key={u.id}><strong>{u.type}</strong><span>{u.stationName} · {fmtDateTime(u.timestamp)}</span><p>{u.notes||'No note'}</p></div>)}</section></div>}
function DispatchPanel({incidents,updates,presence}:{incidents:Incident[];updates:FieldUpdate[];presence:any[]}){return <div className="dispatch-grid"><section className="panel"><span className="section-kicker">DISPATCH BOARD</span><h2>{incidents.length} active incidents</h2>{incidents.map(i=>{const last=updates.find(u=>u.incidentId===i.id);return <div className="dispatch-incident" key={i.id}><div><strong>{i.reportId} · {i.title}</strong><span>{i.status} · {i.urgency}</span></div><small>{last?`${last.type} · ${last.stationName} · ${fmtDateTime(last.timestamp)}`:'No field update'}</small></div>})}</section><section className="panel"><span className="section-kicker">STATIONS</span><h2>Network presence</h2>{presence.slice(0,20).map(p=><div className="presence-row" key={p.id}><div><strong>{p.stationName}</strong><span>{p.role}</span></div><small>{fmtDateTime(p.timestamp)}</small></div>)}</section></div>}
function ConflictPanel({conflicts,onResolve}:{conflicts:SyncConflict[];onResolve:(c:SyncConflict,s:'LOCAL'|'REMOTE')=>void}){const open=conflicts.filter(c=>c.status==='OPEN');return <section className="panel"><span className="section-kicker">CONFLICT INBOX</span><h2>{open.length} unresolved</h2><p className="muted">Equal-version divergent records are never silently merged. Choose the evidence version deliberately.</p>{open.map(c=><div className="conflict-card" key={c.id}><div><strong>{c.entityType} · {c.entityId}</strong><span>Remote: {c.remoteStationId}</span></div><small>Local {c.localUpdatedAt}<br/>Remote {c.remoteUpdatedAt}</small><div><button className="btn secondary" onClick={()=>onResolve(c,'LOCAL')}>Keep local</button><button className="btn primary" onClick={()=>onResolve(c,'REMOTE')}>Accept remote</button></div></div>)}{!open.length&&<p className="muted">No unresolved replication conflicts.</p>}</section>}
function Diagnostics({settings,networkOnline,health,conflicts,updates}:{settings:AppSettings;networkOnline:boolean;health:any;conflicts:SyncConflict[];updates:FieldUpdate[]}){const [storage,setStorage]=useState('checking…');useEffect(()=>{navigator.storage?.estimate?.().then(x=>setStorage(`${Math.round((x.usage||0)/1048576)} MB / ${Math.round((x.quota||0)/1048576)} MB`)).catch(()=>setStorage('unavailable'))},[]);return <div className="network-grid"><section className="panel"><span className="section-kicker">RUNTIME</span><h2>Field readiness</h2><Fact l="Browser online" v={networkOnline?'YES':'NO'}/><Fact l="Local storage" v={storage}/><Fact l="Service worker" v={'serviceWorker' in navigator?'SUPPORTED':'UNAVAILABLE'}/><Fact l="Sync configured" v={settings.syncEnabled?'YES':'NO'}/><Fact l="Sync server" v={health?.ok?'READY':'UNVERIFIED'}/></section><section className="panel"><span className="section-kicker">DATA INTEGRITY</span><h2>Evidence health</h2><Fact l="Open conflicts" v={String(conflicts.filter(c=>c.status==='OPEN').length)}/><Fact l="Field updates" v={String(updates.length)}/><Fact l="Backup version" v="1.0.0"/><p className="muted">Use TOWER → OVERVIEW to export a complete local recovery backup before upgrades or field deployment.</p></section></div>}
